## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("CSVFiles")'
 - julia --color=yes --check-bounds=yes -e 'import Pkg; Pkg.test("CSVFiles"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
